Sim: Extended simulation framework to test against Xilinx MAC
Besides the XGMII loopback that tests Tx and Rx subsystems within the nfmac10g
core a second simulation set up is provided. With the addition of a Tcl script
to generate the Xilinx ten_gig_eth_mac (latest version 15.0.3) two more
simulations are run: (i) Exercise Tx subsystem. Input frames are pushed to the
AXI Tx interface of the nfmac10g. The outbound frames at the xgmii_tx
interface are fed to the xgmii_rx of the Xilinx core. Packets at the AXI Rx
user interface are checked by the Output Check logic. (ii) Exercise Rx
subsystem. The same simulation is run but the nfmac10g and Xilinx cores are
reversed, i.e. Xilinx core sends frames and nfmac10g receives frames.

Simulation is more verbose and all simulations results are collected in a log
file.

diff --git a/sim/utils/Makefile b/sim/utils/Makefile
--- a/sim/utils/Makefile
+++ b/sim/utils/Makefile
@@ -3,16 +3,51 @@
 CC=gcc
 CFLAGS=-Wall -lpcap
 
-top_sim_hdl := nfmac10g_tb
+clean_list := xsim* xelab* xvlog* webtalk* simlog *.dat
 
-.PHONY: clean cleansim gen_stim runsim
+TEST ?= loopback
+top_sim_hdl := nfmac10g_$(TEST)_tb
+
+ifeq ($(TEST),nf2xil)
+	top_sim_hdl := nfmac10g_interoperability_tb
+	xvflags := -d tx=nfmac10g -d rx=xilinx_mac
+endif
+
+ifeq ($(TEST),xil2nf)
+	top_sim_hdl := nfmac10g_interoperability_tb
+	xvflags := -d rx=nfmac10g -d tx=xilinx_mac
+endif
+
+.PHONY: clean cleansim gen_stim runsim siminst
+
+siminst:
+	for ifgi in 0 10 20 ; do \
+		for corr_levli in 0 1 2 ; do \
+			make -s runsim SIMHDL=$(SIMHDL) SRCHDL=$(SRCHDL) PCAP=$(PCAP) TEST=$(TEST) \
+				IFG=$$ifgi CORR_LEVL=$$corr_levli UNDERRUN=0 LOG=$(LOG) ; \
+			simresult=$$? ; \
+			if [ $$simresult -ne 0 ] ; then break ; fi ; \
+		done ; \
+		if [ $$simresult -ne 0 ] ; then \
+			echo "Simulation failed. Check reports"; break; fi ; \
+		for underruni in 1 2 ; do \
+			make -s runsim SIMHDL=$(SIMHDL) SRCHDL=$(SRCHDL) PCAP=$(PCAP) TEST=$(TEST) \
+				IFG=$$ifgi CORR_LEVL=0 UNDERRUN=$$underruni LOG=$(LOG) ; \
+			simresult=$$? ; \
+			if [ $$simresult -ne 0 ] ; then break ; fi ; \
+		done ; \
+		if [ $$simresult -ne 0 ] ; then \
+			echo "Simulation failed. Check reports"; break; fi ; \
+	done; \
+	if [ $$simresult -ne 0 ] ; then false ; fi ;
 
 runsim: gen_stim
-	xvlog $(SRCHDL)/*.v
-	xvlog $(SIMHDL)/*.v
+	echo "\n\n////\nSim: IFG=$(IFG) CORR_LEVL=$(CORR_LEVL) UNDERRUN=$(UNDERRUN)\n////" >> $(LOG)
+	xvlog $(xvflags) $(SRCHDL)/*.v $(SIMHDL)/*.v
 	xelab work.$(top_sim_hdl) -s sim_snapshot
 	xsim -R sim_snapshot > simlog
 	grep -i "SIM OK" simlog || (echo "Simulation failed, see reports"; false)
+	cat simlog >> $(LOG)
 
 gen_stim: pcap2axis cleansim
 	./$< $(PCAP) $(IFG) $(CORR_LEVL) $(UNDERRUN)
@@ -21,7 +56,7 @@ pcap2axis: pcap2axis.c
 	$(CC) -o $@  $< $(CFLAGS)
 
 cleansim:
-	rm -rf xsim* xelab* xvlog* webtalk* simlog *.dat
+	rm -rf $(clean_list)
 
 clean: cleansim
 	rm -f pcap2axis
